import type { Metadata } from "next";
import { Work_Sans } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "./theme/themeContext";
import Header from "./context/Header";

const workSans = Work_Sans({
  variable: "--font-work-sans",
  weight: ["300", "400", "500", "600", "700"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "MetaBlog",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${workSans.variable}`}
      >
        <ThemeProvider>
            <div className="grid grid-cols-12">
            <Header />
                {children}
            </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
